config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'
  get 'password_resets/new'
  get 'password_resets/edit'

  if Rails.env.production?
    get '/404', to: "errors#not_found"
    get '/422', to: "errors#unacceptable"
    get '/500', to: "errors#internal_error"
  end

  class OnlyAjaxRequest
     def matches?(request)
       request.xhr?
     end
  end

  root 'application#home'

  # Fbits Migrations
  get '/fbits-migrations', to: 'fbits_migrations#index'
  get '/fbits-migrations/products-nerus-2-tray', to: 'fbits_migrations#products_nerus_2_tray', as: 'products_nerus_2_tray'
  get '/fbits-migrations/clients', to: 'fbits_migrations#migrate_clients', as: 'migrate_clients'
  get '/fbits-migrations/brands', to: 'fbits_migrations#migrate_brands', as: 'migrate_brands'
  get '/fbits-migrations/categories', to: 'fbits_migrations#migrate_categories', as: 'migrate_categories'
  get '/fbits-migrations/products', to: 'fbits_migrations#migrate_products', as: 'migrate_products'
  get '/fbits-migrations/orders', to: 'fbits_migrations#migrate_orders', as: 'migrate_orders'
  get '/fbits-migrations/orders-yml', to: 'fbits_migrations#migrate_orders_yml', as: 'migrate_orders_yml'

  get '/products' => 'products#index'
  get '/products/:sku' => 'products#index', as: 'product'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'

  get '/login', to:'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/my-profile', to: 'users#my_profile', as: 'my_profile'

  resources :users
  resources :activities
  resources :clients
  resources :orders
  resources :products
  resources :logs, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit ]
  resources :password_resets, only: [:update], defaults: { format: 'js' }
end

app/controllers/fbits_migrations_controller.rb
class FbitsMigrationsController < ApplicationController

	include PicturesSwapHelper
	include NerusHelper
	include FbitsHelper

	def index
		@page = params[:page].nil? ? 0 : params[:page]
		@size = params[:size].nil? ? 50 : params[:size]
	end

	def products_nerus_2_tray
		@products = []
		nerus_grids(pre_creation_list).each do |code, colors|
			colors.each do |color, skus|
				skus.each do |sku, grid|
					if !sku.nil?
						cleanup_categories(sku)
		    		cleanup_images(sku)

		    		product_fbits = ProductFbits.new_from_nerus(grid)
		    		(has_product(sku)) ? edit_product(product_fbits) : create_product(product_fbits)
						
		    		categories = grid_categories(grid)
						create_product_categories(sku, categories)
					end
	    	end
	    	if skus.count > 0
		    	pictures = list_pictures(skus.values.first[:product_number], skus.values.first[:color_code])
		    	create_product_images(skus.values.first[:sku], pictures) if skus.count > 0

		    	product_fbits = ProductFbits.new_from_nerus(skus.values.first)
		    	@products << Product.create_or_update_from_fbits(product_fbits)
				end
			end
			to_review(code)
		end
	end

	def migrate_clients
		fbitisApiService = FbitsApiService.new
		fbits_clients = fbitisApiService.get_clients(params[:page], params[:size])
		clients = Client.populate_from_fbits(fbits_clients)

		clients.each do |client|
			if client.is_a? Object 
				if !client.nil? and client.id != 1073753
					fbits_adresses = fbitisApiService.get_client_adresses(client.id)
					client.adresses = Address.populate_from_fbits(fbits_adresses)
				
					begin
					  client.save
					rescue ActiveRecord::RecordNotSaved => e
					  client.errors.full_messages
					end
				end
			end
		end
		
		respond_to do |format|
      format.js { "" }
		  render json: { page: params["page"].to_i+1, size: params['size'], go: fbits_clients.any?}
    end
  end
				
  def migrate_brands
		fbitisApiService = FbitsApiService.new
		fbits_brands = fbitisApiService.get_brands()

		fbits_brands.each do |fbits_brand|
			brand = Brand.new

			brand.id = fbits_brand['fabricanteId']
			brand.name = fbits_brand['nome']
			brand.status = 1
			
			brand.save!
		end

		respond_to do |format|
      format.js { "" }
		  render json: { page: nil, size: nil, go: nil}
    end
  end

  def migrate_categories
		fbitisApiService = FbitsApiService.new
		fbits_categories = fbitisApiService.get_categories()

		fbits_categories.each do |fbits_category|
			category = Category.new
			
			category.id = fbits_category['id']
			category.name = fbits_category['nome']
			category.parent_id = (fbits_category['categoriaPaiId'] > 0) ? fbits_category['categoriaPaiId'] : nil
			category.erp_id = fbits_category['categoriaERPId']
			category.status = (fbits_category['ativo'] === 'true') ? 1 : 0
			category.url = fbits_category['urlHotSite']
			category.main_category = fbits_category['categoriaPrincipal']
			
			category.save!
		end

		respond_to do |format|
      format.js { "" }
		  render json: { page: nil, size: nil, go: nil}
    end
  end

  def migrate_products
		fbitisApiService = FbitsApiService.new

		fbits_products = fbitisApiService.get_products(params[:page], params[:size])
		fbits_products.each do |fbits_product|
			product = Product.find_or_create_by(external_parent_id: fbits_product["idPaiExterno"])
		
			product.external_parent_id = fbits_product["idPaiExterno"]
			product.external_link_id = fbits_product["idVinculoExterno"]
			product.name = fbits_product["nome"]
			product.sku = fbits_product["sku"]
			product.show_attributes_matrix = fbits_product["exibirMatrizAtributos"]
			product.author = fbits_product["autor"]
			product.editor = fbits_product["editora"]
			product.collection = fbits_product["colecao"]
			product.gender = fbits_product["genero"]
			product.cost_price = fbits_product["precoCusto"]
			product.from_price = fbits_product["precoDe"]
			product.to_price = fbits_product["precoPor"]
			product.delivery_deadline = fbits_product["prazoEntrega"]
			product.is_valid = fbits_product["valido"]
			product.show_site = fbits_product["exibirSite"]
			product.free_shipping = fbits_product["freteGratis"]
			product.free_exchange = fbits_product["trocaGratis"]
			product.weight = fbits_product["peso"]
			product.height = fbits_product["altura"]
			product.length = fbits_product["comprimento"]
			product.width = fbits_product["largura"]
			product.warranty = fbits_product["garantia"]
			product.max_quantity = fbits_product["quantidadeMaximaCompraUnidade"]
			product.min_quantity = fbits_product["quantidadeMinimaCompraUnidade"]
			product.condition = fbits_product["condicao"]
			product.video_url = fbits_product["urlVideo"]

			fbits_categories = fbitisApiService.get_product_categories(product.sku)
			product.categories.destroy_all
			fbits_categories.each do |fbits_category|
				product.categories << Category.find(fbits_category['id']) if fbits_category.include?("id")
			end
			product.save
		end

		respond_to do |format|
	      format.js { "" }
		  render json: { page: params["page"].to_i+1, size: params['size'], go: fbits_products.any?}
    	end
	end

	def migrate_orders
		fbitisApiService = FbitsApiService.new
		fbits_orders = fbitisApiService.get_orders(params[:page], params[:size])

		if fbits_orders.is_a? Array
			File.write("orders/orders_#{params[:page]}.yml", fbits_orders.to_yaml)

			respond_to do |format|
	      format.js { "" }
			  # render json: { page: params["page"].to_i+1, size: params['size'], go: fbits_orders.any?}
			  render json: { page: params["page"].to_i+1, size: params['size'], go: false}
	    end
	  end
	end

	def migrate_orders_yml
		fbitisApiService = FbitsApiService.new
		fbits_orders = YAML.load_file("orders/orders_#{params[:page]}.yml")

		if fbits_orders.is_a? Array
			orders = Order.populate_from_fbits(fbits_orders)

			orders.each do |order|
				debugger if !order.valid?

				begin
				  order.save
				rescue ActiveRecord::RecordNotSaved => e
				  order.errors.full_messages
				end
			end
		end

		respond_to do |format|
      format.js { "" }
		  render json: { page: params["page"].to_i+1, size: params['size'], go: fbits_orders.any?}
    end
	end

end

app/views/fbits_migrations/index.html.erb
<% provide(:title, 'Fbits Migrations') %>
<%= render 'shared/page_heading' %>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				
				<div class="ibox-content">
					<table class="table">
						<thead>
							<th>Dados</th>
							<th>Página</th>
							<th>Tamanho</th>
							<th>Ação</th>
						</thead>
						<tbody>
					  <tr>
					  	<td style="vertical-align: middle;">Clientes e endereços</td>
					  	<td><input type="number" id="client-page-input" class="input-lg" style="width: 100px" value="0"></td>
					  	<td><input type="number" id="client-size-input" class="input-lg" style="width: 100px" value="50" max="50"></td>
					  	<td style="vertical-align: middle;">
					  		<button class="btn btn-xs btn-info dim btn-import" data-type="client" data-url="/fbits-migrations/clients">
					  			<i class="fa fa-download"></i> Importar
								</button>
					  	</td>
					  </tr>
					  <tr>
					  	<td style="vertical-align: middle;">Marcas (Fabricantes)</td>
					  	<td><input type="number" id="brand-page-input" class="input-lg" style="width: 100px" value="0"></td>
					  	<td><input type="number" id="brand-size-input" class="input-lg" style="width: 100px" value="50" max="50"></td>
					  	<td style="vertical-align: middle;">
					  		<button class="btn btn-xs btn-info dim btn-import" data-type="order" data-url="/fbits-migrations/brands">
					  			<i class="fa fa-download"></i> Importar
								</button>
					  	</td>
					  </tr>
					  <tr>
					  	<td style="vertical-align: middle;">Categorias</td>
					  	<td><input type="number" id="category-page-input" class="input-lg" style="width: 100px" value="0"></td>
					  	<td><input type="number" id="category-size-input" class="input-lg" style="width: 100px" value="50" max="50"></td>
					  	<td style="vertical-align: middle;">
					  		<button class="btn btn-xs btn-info dim btn-import" data-type="order" data-url="/fbits-migrations/categories">
					  			<i class="fa fa-download"></i> Importar
								</button>
					  	</td>
					  </tr>
					  <tr>
					  	<td style="vertical-align: middle;">Produtos</td>
					  	<td><input type="number" id="product-page-input" class="input-lg" style="width: 100px" value="0"></td>
					  	<td><input type="number" id="product-size-input" class="input-lg" style="width: 100px" value="50" max="50"></td>
					  	<td style="vertical-align: middle;">
					  		<button class="btn btn-xs btn-info dim btn-import" data-type="product" data-url="/fbits-migrations/products">
					  			<i class="fa fa-download"></i> Importar
								</button>
					  	</td>
					  </tr>
					  <tr>
					  	<td style="vertical-align: middle;">Pedidos</td>
					  	<td><input type="number" id="order-page-input" class="input-lg" style="width: 100px" value="0"></td>
					  	<td><input type="number" id="order-size-input" class="input-lg" style="width: 100px" value="50" max="50"></td>
					  	<td style="vertical-align: middle;">
					  		<button class="btn btn-xs btn-info dim btn-import" data-type="order" data-url="/fbits-migrations/orders">
					  			<i class="fa fa-download"></i> Importar
								</button>
					  	</td>
					  </tr>
					  <tr>
					  	<td style="vertical-align: middle;">Pedidos Yml</td>
					  	<td><input type="number" id="order-yml-page-input" class="input-lg" style="width: 100px" value="0"></td>
					  	<td><input type="number" id="order-yml-size-input" class="input-lg" style="width: 100px" value="50" max="50"></td>
					  	<td style="vertical-align: middle;">
					  		<button class="btn btn-xs btn-info dim btn-import" data-type="order-yml" data-url="/fbits-migrations/orders-yml">
					  			<i class="fa fa-download"></i> Importar
								</button>
					  	</td>
					  </tr>
					  </tbody>
					</table>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal inmodal" id="myModal6" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content modal-content animated flipInY">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Dados importados</h4>
            </div>
            <div class="modal-body" id="modal-body">
                <p><strong><span id='modal-size-span'>10</span> registros, da página <span id="modal-page-span">1</span></strong> importados com sucesso. Aguarde o carregamento da próxima página.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<script>
	function ajax_import(url, page, size) {
		$.ajax({
			type: 'get',
	  	url: url,
	  	data: {page: page, size: size},
			success:function(data){
				$('#myModal6').modal('hide');
				// sleep(2000);
				if (data.go) {
					ajax_import(url, data.page, data.size);
					$('#modal-size-span').html(data.size);
					$('#modal-page-span').html(data.page);
				} else {
					$('#modal-body').html('Todos os registros importados com sucesso! FIM');
				}
				// sleep(2000);
				$('#myModal6').modal('show');
			}
		});
	}

	$(document).ready(function() {
		$('.btn-import').click(function() {
			type = $(this).attr('data-type');
			console.log(type)
			console.log($(this).attr('data-url'))
			console.log($('#'+type+'-page-input').val())
			console.log($('#'+type+'-size-input').val())
			ajax_import($(this).attr('data-url'), $('#'+type+'-page-input').val(), $('#'+type+'-size-input').val())
		});
	});	
</script>

app/views/fbits_migrations/migrate_clients.html.erb
<% provide(:title, 'Fbits Migrations') %>
<%= render 'shared/page_heading' %>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				
				<div class="ibox-content">
<%= @clients.second.adresses.count %>
<p></p>
<%= @adresses %>
					<table class="table">
						<thead>
							<th>Dados</th>
							<th>Ação</th>
						</thead>
						<tbody>
					  <tr>
					  	<td>Clientes</td>
					  	<td>
					  		<%= link_to migrate_clients_path, class: 'btn btn-xs btn-info dim' do %>
					  			<i class="fa fa-download"></i> Importar
	    					<% end %>
					  		</td>
					  </tr>
					  </tbody>
					</table>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/fbits_migrations/products_nerus_2_tray.html.erb
<% provide(:title, 'Fbits Migrations') %>
<%= render 'shared/page_heading' %>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				
				<div class="ibox-content">

<p></p>
					<table class="table">
						<thead>
							<th>Dados</th>
							<th>Ação</th>
						</thead>
						<tbody>
							<% @products.each do |product| %>
					  <tr>
					  	<td><%= product %></td>
					  	<td>
					  		<%= link_to migrate_clients_path, class: 'btn btn-xs btn-info dim' do %>
					  			<i class="fa fa-download"></i> Importar
	    					<% end %>
					  		</td>
					  </tr>
					  <% end %>
					  </tbody>
					</table>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>