config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'
  get 'password_resets/new'
  get 'password_resets/edit'

  if Rails.env.production?
    get '/404', to: "errors#not_found"
    get '/422', to: "errors#unacceptable"
    get '/500', to: "errors#internal_error"
  end

  class OnlyAjaxRequest
     def matches?(request)
       request.xhr?
     end
  end

  root 'application#home'

  # Fbits Migrations
  get '/fbits-migrations', to: 'fbits_migrations#index'
  get '/fbits-migrations/products-nerus-2-tray', to: 'fbits_migrations#products_nerus_2_tray', as: 'products_nerus_2_tray'
  get '/fbits-migrations/clients', to: 'fbits_migrations#migrate_clients', as: 'migrate_clients'
  get '/fbits-migrations/brands', to: 'fbits_migrations#migrate_brands', as: 'migrate_brands'
  get '/fbits-migrations/categories', to: 'fbits_migrations#migrate_categories', as: 'migrate_categories'
  get '/fbits-migrations/products', to: 'fbits_migrations#migrate_products', as: 'migrate_products'
  get '/fbits-migrations/orders', to: 'fbits_migrations#migrate_orders', as: 'migrate_orders'
  get '/fbits-migrations/orders-yml', to: 'fbits_migrations#migrate_orders_yml', as: 'migrate_orders_yml'

  get '/products' => 'products#index'
  get '/products/:sku' => 'products#index', as: 'product'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'

  get '/login', to:'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/my-profile', to: 'users#my_profile', as: 'my_profile'

  resources :users
  resources :activities
  resources :clients
  resources :orders
  resources :products
  resources :logs, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit ]
  resources :password_resets, only: [:update], defaults: { format: 'js' }
end

app/models/user.rb
class User < ApplicationRecord
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.get_current_user }

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  enum role: [:NUB, :super, :admin, :coordenador, :gerente, :vendedor, :mesa, :compras, :financeiro, :RH]

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")

    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  after_initialize do
    if self.new_record?
      self.role ||= :NUB
    end
  end

  private
    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :login_required!, only: [:new, :create]
  layout :resolve_layout

  def index
     @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def my_profile
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:new] = {
        :type => 'success',
        :title => 'Quase lá!',
        :msg => 'Verifique seu e-mail para ativar sua conta.'
      }
      
    	redirect_to login_path + "?nub=1"
    else
			@model = @user
			respond_to do |format|  
      	format.js { render "/shared/show_form_errors" }
      end

    end
  end

  def edit
    @user = authorize User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    authorize @user

    if @user.update(post_params)
      flash[:edit] = {
        :type => 'success',
        :title => 'Ok',
        :msg => 'Seus dados foram editados com sucesso.'
      }
      redirect_to @user
    else
      @model = @user
      respond_to do |format|  
        format.js { render "/shared/show_form_errors" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    authorize @user

    if @user.destroy
      flash[:destroy] = {
        :type => 'success',
        :title => 'Ok',
        :msg => 'Usuário deletado. Hasta la vista, baby!'
      }
    else
     flash[:destroy] = {
        :type => 'error',
        :title => 'Erro',
        :msg => 'Não foi possível deletar, tem certeza que você pode fazer isso?'
      }
    end
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

  	def resolve_layout
      case action_name
      	when "new", "create"
      	  "clean"
    	else
          "application"
    	end
  	end

    def post_params
      params.require(:user).permit(policy(@user).permitted_attributes)
    end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size=80, extra_class=nil, extra_style="")
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=http://adm.anita.com.br/default-profile-icon.png"
    image_tag(gravatar_url, alt: user.name, class: "gravatar #{extra_class}", style: extra_style)
  end

end

app/views/users/_user.html.erb
<tr>
	<td><%= gravatar_for user, 50, nil, 'width:50px' %></td>
  <td><%= link_to user.name, user %></td>
  <td><%= link_to user.email, user %></td>
  <td><%= link_to user.role, user %></td>
  <td>
  	<% if policy(user).update? %>
	    <%= link_to edit_user_path(user), class: 'btn btn-xs btn-info dim' do %>
	    <i class="fa fa-pencil"></i> Editar
	    <% end %>
	  <% end %>
	  <% if policy(user).destroy? %>
	    <%= link_to user, method: :delete, data: { confirm: "Está certo disso?" }, class: 'btn btn-xs btn-danger dim' do %>
	    	<i class="fa fa-trash"></i> Deletar
	    <% end %>
	  <% end %>
	</td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, "Edite Seu perfil") %>
<%= render 'shared/page_heading' %>

<div class="row wrapper wrapper-content animated fadeInRight">
	<div class="col-lg-12">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h3><%= @user.name%></h3>

      </div>

			<div class="ibox-content flex">
				<div class="row">
				  <div class="col-md-6 col-md-offset-3">
				    <%= form_for(@user) do |f| %>
				      <%= render 'shared/error_messages' %>

				      <%= f.label :name %>
				      <%= f.text_field :name, class: 'form-control' %>

				      <%= f.label :email %>
				      <%= f.email_field :email, class: 'form-control' %>

				      <%= f.label :password %>
				      <%= f.password_field :password, class: 'form-control' %>

				      <%= f.label :password_confirmation, "Confirmation" %>
				      <%= f.password_field :password_confirmation, class: 'form-control' %>

				      <%= f.submit "Salvar alterações", class: "btn btn-primary" %>
				    <% end %>

				    <div class="gravatar_edit">
				      <%= gravatar_for @user %>
				      <a href="http://gravatar.com/emails" target="_blank">Trocar foto</a>
				    </div>
				  </div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Usuários do sistema') %>
<%= render 'shared/page_heading' %>

<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<span class="float-right"><%= page_entries_info @users %></span>
				<div class="ibox-content">

					<table class="table">
						<thead>
							<th>Foto</th>
							<th>Usuário</th>
							<th>E-mail</th>
							<th>Permissões</th>
							<th>Ações</th>
						</thead>
						<tbody>
					  <%= render @users %>
					  </tbody>
					</table>
					</ul>

					<%= will_paginate %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/my_profile.html.erb
<% provide(:title, "Meu perfil") %>
<%= render 'shared/page_heading' %>

<div class="row wrapper wrapper-content animated fadeInRight">
	<div class="col-lg-12">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h3><%= @user.name%></h3>

				<div class="ibox-tools">
					<div class="buttons">
						<%= link_to edit_user_path(@user), class: "btn btn-w-m btn-sm btn-success" do %><%= fa "fa-pencil", "fa" %> Editar<% end %>
						<a href="#" class="btn btn-w-m btn-sm btn-info"><i class="fa fa-lock "></i> Alterar senha </a>
					</div>
				</div>
      </div>

			<div class="ibox-content flex">
				<div class="m-r-lg text-center">
					<%= gravatar_for @user, 140, 'img-circle circle-border info m-b-md', "max-width:140px" %>
				</div>
					
				<div class="row">
					<div class="col-lg-6">
						<h4><%= fa 'fa-user-tie' %> Gerente</h4>
						<ul class="list-unstyled m-t-md">
							<li>
								<span class="fa fa-envelope m-r-xs"></span>
					      <label>Email:</label>
					      <%= @user.email %>
			    		</li>
			    		<li>
					      <span class="fa fa-home m-r-xs"></span>
					      <label>Endereço:</label>
					      Rua Melissa, 80 - Carandá Bosque 2<br>
					      Campo Grande / MS CEP: 79032-181
					    </li>
					    <li>
					      <span class="fa fa-phone m-r-xs"></span>
					      <label>Contatos:</label>
					      +55 67 99186-3122
			    		</li>
			    		<h1>
			    			<%= fa "fa-whatsapp-square", "fab" %>
			    			<%= fa "fa-skype", "fab" %>
			    			<%= fa "fa-instagram", "fab" %>
			    			<%= fa "fa-facebook", "fab" %>
			    			<%= fa "fa-linkedin", "fab" %>
			    		</h1>
						</ul>
					</div>
					<div class="col-lg-6">
						<ul class="list-unstyled m-t-md">
		    			<li>
				        <span class="fa fa-building m-r-xs"></span>
				        <label>Departamento:</label>
				        Site
		    			</li>
		    			<li>
				        <span class="fa fa-phone m-r-xs"></span>
				        <label>Ramal:</label>
				        4292
		    			</li>
		    			<li>
				        <span class="fa fa-map-marker-alt m-r-xs"></span>
				        <label>Lotação:</label>
				        Loja 10 (Matriz) - Av. Mato Grosso, 2934
		    			</li>
		    			<li>
				        <span class="fa fa-clock m-r-xs"></span>
				        <label>Expediente:</label>
				        Segunda a sexta da 08:00 às 12:00 / 14:00 às 18:00
		    			</li>
		    			<li>
				        <span class="fa fa-tags m-r-xs"></span>
				        <label>Permissões:</label>
								<span class="label">Suporte</span>
				        <span class="label">Administrador</span>
				        <span class="label">Super usuário</span>
		    			</li>
		    		</ul> 
					</div> 
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Solicite seu acesso') %>
<% provide(:extra_js, (javascript_include_tag 'icheck/icheck', 'data-turbolinks-track': 'reload')) %>

<div class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <div>
                <h1 class="logo-name"><%= image_tag "logo-square-alfa.png", class: "login-logo" %></h1>
            </div>
            <h3 class="m-t-md">Solicitação de acesso</h3>

            <p>Seu acesso ao App será concedido pela diretoria após aprovação e definição do perfil de acordo com suas atribuições.</p>
            <%= form_for(@user, url: signup_path, :html => { class: 'm-t' }) do |f| %>
            
                <div class="form-group" id="user_name_form_group">
                    <%= f.email_field :name, class: 'form-control', placeholder: 'Seu nome', type: 'text' %>
                </div>
                <div class="form-group <%= 'has-error' if @user.errors.include? :email %>" id="user_email_form_group">
                    <%= f.email_field :email, class: 'form-control', placeholder: 'Seu e-mail', type: 'email' %>
                </div>
                <div class="form-group <%= 'has-error' if @user.errors.include? :password %>" id="user_password_form_group">
                    <%= f.password_field :password, class: 'form-control', placeholder: 'Senha' %>
                </div>
                <div class="form-group <%= 'has-error' if @user.errors.include? :password_confirmation %>" id="user_password_confirmation_form_group">
                    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirme sua senha' %>
                </div>
                <div class="form-group">
					<div class="checkbox i-checks text-center">
						<label style="padding-left: 0px;"> <input type="checkbox"><i></i> Concordo que clico sem ler os termos :) </label>
					</div>
                </div>
                <%= f.submit "Solicitar meu acesso", class: "btn btn-primary block full-width m-b" %>

                <p class="text-muted text-center"><small>Já tem seu acesso?</small></p>
                <%= link_to login_url, class: "btn btn-sm btn-white btn-block" do %>
                    Login
                <% end %>

            <% end %>
            <p class="m-t"> <small>The Anita Shoes Admin Rearguard App is based on Inspinia and Bootstrap 4 &copy; <%= Date.current.year %></small> </p>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });
</script>

app/views/users/new2.html.erb
console.log('oewwww');

app/views/users/show.html.erb
<% require 'uri' %>
<% provide(:title, "Meu perfil") %>
<%= render 'shared/page_heading' %>

<div class="row">
	<div class="col-lg-12">
		<div class="wrapper wrapper-content animated fadeInRight">
			<div class="ibox-content p-xl">
				<h1>
				  <%= gravatar_for @user %>
				  <%= @user.name %>
				  <small><%= @user.email %></small>
				</h1>
			</div>
		</div>
	</div>
</div>