config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'
  get 'password_resets/new'
  get 'password_resets/edit'

  if Rails.env.production?
    get '/404', to: "errors#not_found"
    get '/422', to: "errors#unacceptable"
    get '/500', to: "errors#internal_error"
  end

  class OnlyAjaxRequest
     def matches?(request)
       request.xhr?
     end
  end

  root 'application#home'

  # Fbits Migrations
  get '/fbits-migrations', to: 'fbits_migrations#index'
  get '/fbits-migrations/products-nerus-2-tray', to: 'fbits_migrations#products_nerus_2_tray', as: 'products_nerus_2_tray'
  get '/fbits-migrations/clients', to: 'fbits_migrations#migrate_clients', as: 'migrate_clients'
  get '/fbits-migrations/brands', to: 'fbits_migrations#migrate_brands', as: 'migrate_brands'
  get '/fbits-migrations/categories', to: 'fbits_migrations#migrate_categories', as: 'migrate_categories'
  get '/fbits-migrations/products', to: 'fbits_migrations#migrate_products', as: 'migrate_products'
  get '/fbits-migrations/orders', to: 'fbits_migrations#migrate_orders', as: 'migrate_orders'
  get '/fbits-migrations/orders-yml', to: 'fbits_migrations#migrate_orders_yml', as: 'migrate_orders_yml'

  get '/products' => 'products#index'
  get '/products/:sku' => 'products#index', as: 'product'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'

  get '/login', to:'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/my-profile', to: 'users#my_profile', as: 'my_profile'

  resources :users
  resources :activities
  resources :clients
  resources :orders
  resources :products
  resources :logs, only: [:index]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit ]
  resources :password_resets, only: [:update], defaults: { format: 'js' }
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<script>
  $(document).ready(function() {
    <% flash.each do |key, value| %>
      show_flash('<%= value.to_json.html_safe %>')
    <% end %>
  });
</script>

app/views/shared/_footer.html.erb
<div class="footer fixed">
    <div class="pull-right">
        <strong>12.324</strong> produtos sincronizados
    </div>
    <div>
        <strong>Copyright</strong> Tobelli Comércio de Calçados &copy; <%= Time.now.year %>
    </div>
</div>

app/views/shared/_header.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " data-remote="true" href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" action="search_results.html">
                <div class="form-group">
                    <input type="text" placeholder="Busque o que quiser" class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <%= link_to logout_path, rel: 'nofollow', 'data-method': 'delete' do %>
                <!-- <a href="/logout" rel="nofollow" data-method="delete"> -->
                    <i class="fa fa-sign-out"></i> Sair
                <!-- </a> -->
                <% end %>
            </li>
<!--             <li>
                <a class="right-sidebar-toggle">
                    <i class="fa fa-tasks"></i>
                </a>
            </li> -->
        </ul>
    </nav>
</div>

app/views/shared/_page_heading.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2><%= yield :title %></h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to root_path do %>Painel<% end %>
            </li>
            <li class="active">
                <strong><%= yield :title %></strong>
            </li>
        </ol>
    </div>
</div>

app/views/shared/_sidebar.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element text-center">
                    <span>
                        <%= image_tag "logo-square-alfa.png", class: "img-circle sidebar-profile" %>
                        <%#= gravatar_for current_user, 48, "img-circle" %>
                    </span>
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle text-left">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold"><%= session[:user_name] %></strong>
                            </span>
                            <span class="text-muted text-xs block"><%= fa 'fa-user-tie' %>Gerente<b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><%= link_to my_profile_path do %>Meu perfil<% end %></li>
                        <!-- <li><a href="contacts.html">Contacts</a></li>
                        <li><a href="mailbox.html">Mailbox</a></li> -->
                        <li class="divider"></li>
                        <li><a href="login.html">Sair</a></li>
                    </ul>
                </div>
            </li>
            <li class="<%= 'active' if active_link?('application', 'home') %>">
                <%= link_to root_path do %>
                    <i class="fa fa-tachometer-alt"></i> <span class="nav-label">Painel</span>
                <% end %>
            </li>
            
            <!-- E-COMMERCE -->
            <li class="<%= 'mm-active' if show_group?('ecommerce') %>">
                <a href="#" aria-expanded="<%= show_group?('ecommerce') ? 'true' : 'false' %>">
                    <i class="fa fa-cart-plus"></i> <span class="nav-label">E-commerce</span><span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level <%#= 'mm-collapse mm-show' if show_group?('ecommerce') %>" aria-expanded="<%= show_group?('ecommerce') ? 'true' : 'false' %>">
                    <li class="<%= 'active' if active_link?('products', 'index') %>"><%= link_to products_path do %><i class="fa fa-boxes"></i>Produtos<% end %></li>
                    <li class="<%= 'active' if active_link?('clients', 'index') %>"><%= link_to clients_path do %><i class="fa fa-users"></i>Clientes<% end %></li>
                    <li class="<%= 'active' if active_link?('orders', 'index') %>"><%= link_to orders_path do %><i class="fa fa-file-invoice-dollar"></i>Pedidos<% end %></li>
                </ul>
            </li>

            <!-- CONFIGURAÇÕES -->
            <li class="<%= 'mm-active' if show_group?('configurations') %>">
                <a href="#" aria-expanded="<%= show_group?('configurations') ? 'true' : 'false' %>"><i class="fa fa-cogs"></i> <span class="nav-label">Configurações</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level <%#= 'mm-show' if show_group?('configurations') %>"  aria-expanded="<%= show_group?('configurations') ? 'true' : 'false' %>">
                    <li class="<%= 'active' if active_link?('users', 'index') %>"><%= link_to users_path do %><i class="fa fa-users"></i>Usuários<% end %></li>
                    <li class="<%= 'active' if active_link?('activities', 'index') %>"><%= link_to activities_path do %><i class="fa fa-history"></i>Log de uso<% end %></li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

app/views/shared/show_form_errors.erb
$(document).ready(function () {
	$('.form-control').focus(function() {
		$('#'+$(this).attr('id')+'_form_group').removeClass('has-error');
		$('.'+$(this).attr('id')+'_error').hide();
	});
});

msg = "Encontramos <strong><%= pluralize(@model.errors.count, "erro")%></strong> nisto que foi informado :(";
js_flash("error", "Revise os dados informados", msg);

$('.error').remove();
<% @model.errors.each do |attribute, error| %>
	$('#<%= @model.class.name.downcase %>_<%= attribute %>_form_group').addClass('has-error');
	$('#<%= @model.class.name.downcase %>_<%= attribute %>').after($('<label class="error <%= @model.class.name.downcase %>_<%= attribute %>_error" id="error_explanation">- <%= error.capitalize %></label>'));
<% end %>